Revise HttpRequestFunctionConfiguration configuration
spring-cloud/stream-applications pull request #295
Opened 2022-05-30 18:20 UTC by sunny151091

Fixes #286

2022-05-30 18:20 UTC, pivotal-cla commented
@sunny151091 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/stream-applications&pullRequestId=295)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/stream-applications&pullRequestId=295) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-05-30 18:33 UTC, pivotal-cla commented
@sunny151091 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/stream-applications&pullRequestId=295)!

2022-05-31 03:13 UTC, onobc requested changes
Nice work @sunny151091 !

There are few items to address but all small things. 

One thing  I would recommend (I do this myself anytime I change an app) is to build the specific rabbit/kafka version of the app and run it locally. It's a great verification (although we do cover that case during out CI builds) and also a good leaning tool to see how the apps are actually constructed. 


The process is outlined in the readme. Just to summarize, the content in each `applications/<source|sink|processor>/<appname>` is a template that brings in some function dependencies (and other deps) and we run the app generator plugin on that which in turn creates 2 apps under `applications/<source|sink|processor>/<appname>/apps` - take a look in there a see what you see. You can then drop into the rabbit/kafka apps and build/run those and see the final app actually working like it does when its downloaded from maven/docker by end users.

2022-05-31 03:13 UTC, onobc commented on applications/processor/http-request-processor/src/main/resources/META-INF/dataflow-configuration-metadata.properties
> +configuration-properties.names=maximumBufferSize
The format for the value is the full path to the alternate config prop, which in this case is [spring.codec.max-in-memory-size](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/codec/CodecProperties.java#L28). 

You can take a look at another example in the JdbcSource app I pointed to as an example in my original reply.

2022-05-31 03:13 UTC, onobc commented on applications/processor/http-request-processor/src/main/resources/META-INF/dataflow-configuration-metadata.properties
> +configuration-properties.names=maximumBufferSize
There is also another "eventually-to-be-deprecated" with a similar name in this directory, can you please update it as well?

2022-05-31 03:13 UTC, onobc commented on functions/function/http-request-function/src/main/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionProperties.java
> -	private int maximumBufferSize = 256 * 1024;
I typically would recommend that we add a unit test to cover this removal but there is currently no coverage for this particular property as it is difficult to verify anyways. Also, we can trust that the WebClient spring.codecs property has been thoroughly tested.

2022-05-31 15:49 UTC, artembilan requested changes
This is great even if we have a couple concerns.

Thanks

2022-05-31 15:49 UTC, artembilan commented on functions/function/http-request-function/src/main/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionConfiguration.java
> +			this.webClient = webClientBuilder.build();
I think there was a reason in Spring Boot to not expose a `WebClient` as a bean. Therefore having a `WebClient.Builder` injected is OK.
And then we use it internally to create a respective instance as it is intended.

This is already some breaking change. Therefore I didn't mark the issue to be included in the current version.
For the future version it is fully OK to drop our property and remove `WebClient` bean.

2022-05-31 19:31 UTC, artembilan approved these changes

2022-05-31 19:32 UTC, artembilan approved these changes
I don't have any more concerns unless we would like to revise that new property to the whole `org.springframework.boot.autoconfigure.codec.CodecProperties` class to expose.

Let's see what @onobc thinks on the matter!

2022-06-01 05:16 UTC, onobc commented on functions/function/http-request-function/src/main/java/org/springframework/cloud/fn/http/request/HttpRequestFunctionConfiguration.java
> +			this.webClient = webClientBuilder.build();
> I think there was a reason in Spring Boot to not expose a WebClient as a bean. Therefore having a WebClient.Builder injected is OK.

Agreed @artembilan . I meant just passing in the WebClient to the `HttpRequestFunction.init` as it was being done before (like [this](https://github.com/spring-cloud/stream-applications/pull/295/files#diff-f40508500c04ef15efaf5299bc78fcdda9485a34386a76c0af0b75aa903151dfR52)).

2022-06-01 05:19 UTC, onobc commented on applications/processor/http-request-processor/src/main/resources/META-INF/dataflow-configuration-metadata.properties
> +configuration-properties.names=maximumBufferSize
@artembilan If all of the properties apply to the `WebClient` then that would be a great thing to do. 

@sunny151091 - this adjustment would result in all of the properties in `CodecProperties ` to be listed in the app docs (vs. only the single one that I suggested to add initially).

2022-06-01 05:25 UTC, onobc requested changes
Thanks for the updates @sunny151091 . Looking good. 

These are the only 2 items remaining: 
1. I think we should update the metadata files to use the `CodecProperties` (vs. the single property).
2. I am concerned that I do not see any updated apps docs in the PR (see my comment about this:
> When you build in the project it auto-generates docs based on these files. This change should have resulted in a change to the generated docs. I believe the doc generation will ignore any props it can not resolve which explains why there was no update. See what happens after you update it as outlined above and re-run the build.

2022-06-01 13:11 UTC, onobc commented
>Hi @onobc, have added CodecProperties. But i don't know which doc will get auto-generated after building the application.
After making the changes i re-build the http-request-function and the build was successful. However no docs were auto-generated.
Could you help me out here?

Hi @sunny151091 ,

Just run the build from the root directory as described at the top of [Build](https://github.com/spring-cloud/stream-applications/blob/main/README.adoc#build) section in the README. This should generate the docs and also execute the related app tests.

Thanks

2022-06-02 14:16 UTC, artembilan approved these changes
Hi @sunny151091 !

I'm not @onobc , but I want to say you "Thank you!" for such a great contribution!

I just want to leave this comment about my personal contribution cycle preferences.

So, you said:

> Have committed the auto generated app docs. 

However we definitely see a new commit from you therefore not need to duplicate a message on the matter. 
Unless we forget about your PR for a long time 😉 

Also: if you agree with our review, no reason to say that: just push the fix which really confirm an agreement!
Otherwise it turns to a spam in my mailbox but I have to deal with hundreds of PRs or GH issue sometime...

In addition, just for future considerations. We try to follow these Git commit rules: https://cbea.ms/git-commit/.
Of course we will fix the commit message on merge, but it would save yours and ours time during PR preparing and review, plus merging.

Thanks for understanding!

Re. your PR: all good, but we cannot merge it yet because we haven't switched `main` branch to new major or minor version. We cannot apply this change to the point version since it comes as a breaking change.

2022-06-02 14:41 UTC, onobc approved these changes

2022-06-02 17:59 UTC, sunny151091 commented
Thanks a lot @onobc and @artembilan. 

This was my first ever contribution to open source. I will take a note of all the feedback you guys shared and adhere to the contribution guidelines in my future contributions.

2022-06-21 18:15 UTC, onobc commented
@sunny151091 
We will be creating a branch for the next release (`2022.0.0`) shortly and will merge this in at that point. 

Thanks again for the contribution.

2022-07-16 00:01 UTC, merged