Update to Spring Boot 3.4.1
spring-cloud/stream-applications pull request #600
Opened 2024-12-19 20:55 UTC by onobc

This commit updates the following dependencies:
- Spring Boot to 3.4.1
- Spring Framework to 6.2.1
- Spring Cloud 2024.0.0
- Spring Cloud Function 4.2.0
- Spring Cloud Stream 4.2.0

Resolves #599

2024-12-19 20:57 UTC, artembilan requested changes

2024-12-19 20:57 UTC, artembilan commented on stream-applications-build/pom.xml
> +        <spring-cloud-stream-dependencies.version>4.2.0</spring-cloud-stream-dependencies.version>
I wonder why do we need these two if we have already Spring Cloud BOM?
Not familiar with Cloud Starter, but might be same story.

2024-12-19 21:34 UTC, artembilan requested changes
According to the CI/CD build it looks like something has to be installed first:
```
Error:  Failed to execute goal on project zeromq-sink-kafka: Could not resolve dependencies for project org.springframework.cloud.stream.app:zeromq-sink-kafka:jar:6.0.0-SNAPSHOT: The following artifacts could not be resolved: org.springframework.cloud.stream.app:stream-applications-composite-function-support:jar:6.0.0-SNAPSHOT, org.springframework.cloud.stream.app:stream-applications-micrometer-common:jar:6.0.0-SNAPSHOT, org.springframework.cloud.stream.app:stream-applications-security-common:jar:6.0.0-SNAPSHOT, org.springframework.cloud.stream.app:stream-applications-postprocessor-common:jar:6.0.0-SNAPSHOT: org.springframework.cloud.stream.app:stream-applications-composite-function-support:jar:6.0.0-SNAPSHOT was not found in https://repo.spring.io/snapshot during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spring-snapshots has elapsed or updates are forced
```

2024-12-23 21:03 UTC, artembilan requested changes
Thanks, Chris, for doing this!
In general, this is OK, but I wonder if my comments make sense, at least for the future consideration.

2024-12-23 21:03 UTC, artembilan commented on stream-applications-build/pom.xml
> +		<okhttp3.version>4.12.0</okhttp3.version>
Something is off with indents here.

Plus: any chances to know the reasoning behind Spring Boot has removed management for this dep?
Perhaps there is something "in favor of", which we should consider ourselves as well.

2024-12-23 21:03 UTC, artembilan commented on stream-applications-build/pom.xml
>          <testcontainers.version>1.19.8</testcontainers.version>
Not related, but I believe Testcontainers is managed by Spring Boot.

2025-01-06 17:13 UTC, onobc commented on stream-applications-build/pom.xml
> +        <spring-cloud-stream-dependencies.version>4.2.0</spring-cloud-stream-dependencies.version>
Yes, I think these are no longer needed and were previously here to override versions to handle old CVEs. I will remove the unnecessary ones.

2025-01-06 18:40 UTC, onobc commented on stream-applications-build/pom.xml
> +        <spring.version>6.2.1</spring.version>
I added comment explaining why in the pom.xml on latest commit (basically used in release train to get version for some doc that is generated). Not ideal, but that is how it is right now.

2025-01-06 18:40 UTC, onobc commented on stream-applications-build/pom.xml
> +        <spring-cloud-stream-dependencies.version>4.2.1-SNAPSHOT</spring-cloud-stream-dependencies.version>
Agreed, no longer needed. Adjusted in latest commit.

2025-01-06 18:41 UTC, onobc commented on stream-applications-build/pom.xml
> +		<okhttp3.version>4.12.0</okhttp3.version>
The release notes simply say that they no longer have a dependency on it so have removed dep mgmt for it.

2025-01-06 18:41 UTC, onobc commented on stream-applications-build/pom.xml
>          <testcontainers.version>1.19.8</testcontainers.version>
Yep - agreed. This was old holdover from a previous required override. I will update now.

2025-01-06 18:43 UTC, onobc commented on applications/sink/elasticsearch-sink/src/test/java/org/springframework/cloud/stream/app/sink/elasticsearch/ElasticsearchSinkTests.java
> -	@Configuration(proxyBeanMethods = false)
Yep, good ask, my bad for lack of explanation. It was dead code that was not being used and is no longer needed. Nothing was actually using the config.

2025-01-06 19:12 UTC, onobc commented
The CI is still failing due to the unmerged spring-cloud-function fix. Once that is merged this should go 💚

2025-01-06 19:15 UTC, artembilan requested changes

2025-01-06 19:15 UTC, artembilan commented on stream-applications-build/pom.xml
> +			</dependency>
All good, Chris!
But what is going on with indents?
Not all of them are tabs?

2025-01-06 21:23 UTC, artembilan requested changes

2025-01-06 21:23 UTC, artembilan commented on applications/stream-applications-core/pom.xml
> +        <java-functions.version>5.1.0-SNAPSHOT</java-functions.version>
Looks like this PR is also fixing https://github.com/spring-cloud/stream-applications/issues/603.
Would you mind to mention that as a `Fixes: #603` sentence in the commit message?

2025-01-07 17:52 UTC, artembilan commented
Spring Cloud Function fix has been merged, but PR build still fails and no clue from those logs why 😢

2025-01-08 17:55 UTC, onobc commented
> Spring Cloud Function fix has been merged, but PR build still fails and no clue from those logs why 😢

I will dig into a figure out what is going on.

2025-01-08 17:57 UTC, onobc commented on stream-applications-build/pom.xml
> +			</dependency>
It only seems to be in xml files. I wiill check my format settings.

2025-01-09 14:55 UTC, merged